import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Anchor,
  Apple,
  Armchair,
  Award,
  Backpack,
  Banana,
  BarChart3,
  Bath,
  Bed,
  Bell,
  Bike,
  Bird,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Bus,
  Cake,
  Camera,
  Candy,
  Car,
  Cat,
  Cherry,
  Code2,
  Coffee,
  Compass,
  Cookie,
  Crown,
  Dice3,
  Dice5,
  Dog,
  Dumbbell,
  Egg,
  FerrisWheel,
  Film,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Laptop,
  Leaf,
  Lightbulb,
  Mail,
  Medal,
  MessageCircle,
  Mic,
  Microscope,
  Moon,
  Music,
  Newspaper,
  Palette,
  PawPrint,
  Phone,
  Pill,
  Pizza,
  Plane,
  Podcast,
  Puzzle,
  Rocket,
  Sailboat,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Target,
  Tent,
  Terminal,
  Timer,
  Trees,
  Trophy,
  TreeDeciduous,
  Tv,
  UtensilsCrossed,
  Volleyball,
  Wallet,
  Waves,
  Zap,
  Droplets,
} from "lucide-react";

const ICON_ENTRY = [
  { name: "Activity", Icon: Activity },
  { name: "Brain", Icon: Brain },
  { name: "Dumbbell", Icon: Dumbbell },
  { name: "Footprints", Icon: Footprints },
  { name: "Heart", Icon: Heart },
  { name: "HeartPulse", Icon: HeartPulse },
  { name: "Medal", Icon: Medal },
  { name: "Microscope", Icon: Microscope },
  { name: "Pill", Icon: Pill },
  { name: "Stethoscope", Icon: Stethoscope },
  { name: "Timer", Icon: Timer },
  { name: "Volleyball", Icon: Volleyball },
] as const;

const ICON_FOOD = [
  { name: "Apple", Icon: Apple },
  { name: "Banana", Icon: Banana },
  { name: "Cake", Icon: Cake },
  { name: "Candy", Icon: Candy },
  { name: "Cherry", Icon: Cherry },
  { name: "Coffee", Icon: Coffee },
  { name: "Cookie", Icon: Cookie },
  { name: "Egg", Icon: Egg },
  { name: "Pizza", Icon: Pizza },
  { name: "UtensilsCrossed", Icon: UtensilsCrossed },
] as const;

const ICON_NATURE = [
  { name: "Bird", Icon: Bird },
  { name: "Cat", Icon: Cat },
  { name: "Dog", Icon: Dog },
  { name: "Droplets", Icon: Droplets },
  { name: "Flame", Icon: Flame },
  { name: "Flower2", Icon: Flower2 },
  { name: "Leaf", Icon: Leaf },
  { name: "Moon", Icon: Moon },
  { name: "PawPrint", Icon: PawPrint },
  { name: "Snowflake", Icon: Snowflake },
  { name: "Sun", Icon: Sun },
  { name: "Trees", Icon: Trees },
  { name: "TreeDeciduous", Icon: TreeDeciduous },
  { name: "Waves", Icon: Waves },
  { name: "Zap", Icon: Zap },
] as const;

const ICON_TRAVEL = [
  { name: "Anchor", Icon: Anchor },
  { name: "Backpack", Icon: Backpack },
  { name: "Bike", Icon: Bike },
  { name: "Bus", Icon: Bus },
  { name: "Car", Icon: Car },
  { name: "Compass", Icon: Compass },
  { name: "FerrisWheel", Icon: FerrisWheel },
  { name: "Flag", Icon: Flag },
  { name: "Globe", Icon: Globe },
  { name: "Plane", Icon: Plane },
  { name: "Rocket", Icon: Rocket },
  { name: "Sailboat", Icon: Sailboat },
  { name: "Tent", Icon: Tent },
] as const;

const ICON_WORK = [
  { name: "BarChart3", Icon: BarChart3 },
  { name: "BookOpen", Icon: BookOpen },
  { name: "Briefcase", Icon: Briefcase },
  { name: "Code2", Icon: Code2 },
  { name: "GraduationCap", Icon: GraduationCap },
  { name: "Laptop", Icon: Laptop },
  { name: "Lightbulb", Icon: Lightbulb },
  { name: "Mail", Icon: Mail },
  { name: "Newspaper", Icon: Newspaper },
  { name: "Terminal", Icon: Terminal },
] as const;

const ICON_LEISURE = [
  { name: "Award", Icon: Award },
  { name: "Camera", Icon: Camera },
  { name: "Crown", Icon: Crown },
  { name: "Dice3", Icon: Dice3 },
  { name: "Dice5", Icon: Dice5 },
  { name: "Film", Icon: Film },
  { name: "Gamepad2", Icon: Gamepad2 },
  { name: "Gem", Icon: Gem },
  { name: "Gift", Icon: Gift },
  { name: "Headphones", Icon: Headphones },
  { name: "Mic", Icon: Mic },
  { name: "Music", Icon: Music },
  { name: "Palette", Icon: Palette },
  { name: "Podcast", Icon: Podcast },
  { name: "Puzzle", Icon: Puzzle },
  { name: "Sparkles", Icon: Sparkles },
  { name: "Star", Icon: Star },
  { name: "Target", Icon: Target },
  { name: "Trophy", Icon: Trophy },
  { name: "Tv", Icon: Tv },
] as const;

const ICON_HOME = [
  { name: "Armchair", Icon: Armchair },
  { name: "Bath", Icon: Bath },
  { name: "Bed", Icon: Bed },
  { name: "Bell", Icon: Bell },
  { name: "Brush", Icon: Brush },
  { name: "Home", Icon: Home },
  { name: "MessageCircle", Icon: MessageCircle },
  { name: "Phone", Icon: Phone },
  { name: "ShoppingCart", Icon: ShoppingCart },
  { name: "Smartphone", Icon: Smartphone },
  { name: "Wallet", Icon: Wallet },
] as const;

export const LUCIDE_PICKER_ICON_GROUPS = [
  { title: "Здоровье и спорт", icons: ICON_ENTRY },
  { title: "Еда и напитки", icons: ICON_FOOD },
  { title: "Природа и животные", icons: ICON_NATURE },
  { title: "Транспорт и путешествия", icons: ICON_TRAVEL },
  { title: "Работа и учёба", icons: ICON_WORK },
  { title: "Досуг и медиа", icons: ICON_LEISURE },
  { title: "Дом и быт", icons: ICON_HOME },
] as const;

export type LucidePickerIconGroup = (typeof LUCIDE_PICKER_ICON_GROUPS)[number];

export const CATEGORY_PICKER_ICONS = LUCIDE_PICKER_ICON_GROUPS.flatMap(
  (g) => g.icons,
);

export type CategoryPickerIconName =
  (typeof CATEGORY_PICKER_ICONS)[number]["name"];

const byName = new Map(
  CATEGORY_PICKER_ICONS.map((e) => [e.name, e] as const),
);

export const getCategoryPickerIconEntry = (name: string) => byName.get(name);

export const DEFAULT_CUSTOM_ICON_NAME: CategoryPickerIconName = "Sparkles";
