import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Armchair,
  Backpack,
  Bath,
  Bed,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Bus,
  Camera,
  Car,
  Code2,
  Coffee,
  Dumbbell,
  Film,
  Flame,
  Gamepad2,
  Gift,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Laptop,
  Leaf,
  Lightbulb,
  Mail,
  MessageCircle,
  Mic,
  Moon,
  Music,
  Newspaper,
  Palette,
  Phone,
  Pill,
  Plane,
  Puzzle,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Sun,
  Tent,
  Terminal,
  Trees,
  Trophy,
  Tv,
  UtensilsCrossed,
  Wallet,
  Waves,
  Zap,
} from "lucide-react";

const ENTRIES = [
  { name: "Activity", Icon: Activity },
  { name: "Armchair", Icon: Armchair },
  { name: "Backpack", Icon: Backpack },
  { name: "Bath", Icon: Bath },
  { name: "Bed", Icon: Bed },
  { name: "Bike", Icon: Bike },
  { name: "BookOpen", Icon: BookOpen },
  { name: "Brain", Icon: Brain },
  { name: "Briefcase", Icon: Briefcase },
  { name: "Brush", Icon: Brush },
  { name: "Bus", Icon: Bus },
  { name: "Camera", Icon: Camera },
  { name: "Car", Icon: Car },
  { name: "Code2", Icon: Code2 },
  { name: "Coffee", Icon: Coffee },
  { name: "Dumbbell", Icon: Dumbbell },
  { name: "Film", Icon: Film },
  { name: "Flame", Icon: Flame },
  { name: "Gamepad2", Icon: Gamepad2 },
  { name: "Gift", Icon: Gift },
  { name: "GraduationCap", Icon: GraduationCap },
  { name: "Headphones", Icon: Headphones },
  { name: "Heart", Icon: Heart },
  { name: "Home", Icon: Home },
  { name: "Laptop", Icon: Laptop },
  { name: "Leaf", Icon: Leaf },
  { name: "Lightbulb", Icon: Lightbulb },
  { name: "Mail", Icon: Mail },
  { name: "MessageCircle", Icon: MessageCircle },
  { name: "Mic", Icon: Mic },
  { name: "Moon", Icon: Moon },
  { name: "Music", Icon: Music },
  { name: "Newspaper", Icon: Newspaper },
  { name: "Palette", Icon: Palette },
  { name: "Phone", Icon: Phone },
  { name: "Pill", Icon: Pill },
  { name: "Plane", Icon: Plane },
  { name: "Puzzle", Icon: Puzzle },
  { name: "ShoppingCart", Icon: ShoppingCart },
  { name: "Smartphone", Icon: Smartphone },
  { name: "Sparkles", Icon: Sparkles },
  { name: "Stethoscope", Icon: Stethoscope },
  { name: "Sun", Icon: Sun },
  { name: "Tent", Icon: Tent },
  { name: "Terminal", Icon: Terminal },
  { name: "Trees", Icon: Trees },
  { name: "Trophy", Icon: Trophy },
  { name: "Tv", Icon: Tv },
  { name: "UtensilsCrossed", Icon: UtensilsCrossed },
  { name: "Wallet", Icon: Wallet },
  { name: "Waves", Icon: Waves },
  { name: "Zap", Icon: Zap },
] as const satisfies ReadonlyArray<{ name: string; Icon: LucideIcon }>;

export type CategoryPickerIconName = (typeof ENTRIES)[number]["name"];

export const CATEGORY_PICKER_ICONS = ENTRIES;

const byName = new Map(ENTRIES.map((e) => [e.name, e] as const));

export const getCategoryPickerIconEntry = (name: string) => byName.get(name);

export const DEFAULT_CUSTOM_ICON_NAME: CategoryPickerIconName = "Sparkles";
